require.config({
    'baseUrl':'js',
    'paths':{
        'jquery':'jquery.min',
        'index':'index',
    },
    'shim':{
        'index':{
            'deps':['jquery']
        }
    }
})
require(['index'],function(index){
})